.PHONY: all clean depend distclean

include ../../mak/module.mak
APP=main
include ../../mak/app.mak

all: module-all app-all
clean: module-clean app-clean
depend: module-depend
distclean: module-distclean
